#!/usr/bin/env python3
"""Guard the paper's rule that no experimental number is written by hand.

Every measured value in the paper is a macro from `numbers.tex`, regenerated by
`analysis/make_numbers.py` at build time, so re-running an analysis updates the
PDF and a stale figure is impossible. The rule only holds if nothing slips
through, and the failure is silent: a hand-typed 76.1 stays 76.1 forever while
the analysis that produced it moves on. This is the kind of error that survives
every proofread, because the sentence still reads correctly.

Two checks:

* every `\\Macro{}` used in the paper sources is defined in `numbers.tex` (a
  missing one is a LaTeX error anyway, but this names it plainly); and
* no bare decimal or percentage appears in the prose outside maths, comments and
  a short allowlist of design constants --- the k-ladder, model sizes, sampling
  settings, and similar things that describe the experiment rather than report
  its outcome.

Run standalone or from `paper/build.sh`. Exits non-zero on an undefined macro,
which is a real breakage; a suspicious bare number is reported as a warning,
since the allowlist cannot anticipate every legitimate constant.

Usage:  python scripts/check_numbers.py
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SOURCES = ["paper/main.tex", "paper/results_body.tex", "paper/discussion_body.tex"]

# Constants that describe the design rather than report a measurement.
ALLOWED = {
    "0", "1", "2", "3", "4", "5", "6", "7", "8", "12", "16", "18", "24", "32",
    "48", "50", "64", "96", "128", "146", "180", "602", "2048", "8192",
    "0.5", "0.6", "0.75", "0.8", "0.85", "0.9", "1.0", "1.05", "1.7", "2.5",
    "5.0", "12.5", "25", "26", "95",
}


def main() -> int:
    numbers = REPO / "paper/numbers.tex"
    if not numbers.exists():
        print("[numbers] paper/numbers.tex missing; run analysis/make_numbers.py")
        return 1
    defined = set(re.findall(r"\\newcommand\{\\([A-Za-z]+)\}", numbers.read_text()))

    used: set[str] = set()
    warnings: list[str] = []
    pat = re.compile(
        r"(?<![\\A-Za-z0-9.])(\d+\.\d+|\d+)\\?%|(?<![\\A-Za-z0-9.])(\d+\.\d+)(?![\d}])")

    for rel in SOURCES:
        path = REPO / rel
        if not path.exists():
            continue
        text = path.read_text()
        used |= set(re.findall(r"\\([A-Z][A-Za-z]*)\{\}",
                               re.sub(r"(?m)^\s*%.*$", "", text)))
        for i, line in enumerate(text.split("\n"), 1):
            if line.strip().startswith("%") or "includegraphics" in line:
                continue
            for m in pat.finditer(re.sub(r"\$[^$]*\$", "", line)):
                v = m.group(1) or m.group(2)
                if v and v not in ALLOWED:
                    warnings.append(f"{rel}:{i}: bare number {v!r} -- "
                                    f"should this be a macro? {line.strip()[:70]}")
            # Maths was stripped above, and that is where a hand-typed number
            # hides: `$n=90$` sat in the body for weeks, the one experimental
            # value in the paper that was not a macro, and this check could not
            # see it. Decimals inside maths are almost always measurements;
            # integers inside maths are almost always the design (k values,
            # periods, model counts), so only decimals are flagged, and
            # exponents like 4\times10^{-4} are excluded by the guard on ^{.
            for m in re.finditer(r"\$([^$]*)\$", line):
                for n in re.finditer(r"(?<![\\A-Za-z0-9.^{])(\d+\.\d+)", m.group(1)):
                    if n.group(1) not in ALLOWED:
                        warnings.append(
                            f"{rel}:{i}: bare number {n.group(1)!r} inside maths -- "
                            f"should this be a macro? {line.strip()[:70]}")

    missing = sorted(used - defined)
    if missing:
        print(f"[numbers] FAIL: used but undefined: {', '.join(missing)}")
        return 1
    for w in warnings:
        print(f"[numbers] warning: {w}")
    print(f"[numbers] OK  {len(used)} macros used, all defined"
          + (f"; {len(warnings)} bare numbers to eyeball" if warnings else ""))
    return 0


if __name__ == "__main__":
    sys.exit(main())
