#!/usr/bin/env python3
"""Generate numbers_extra.tex: workspace-only macros the frozen numbers.tex
lacks. Reads the same result JSONs the main pipeline reads; nothing is typed
by hand. Run from anywhere:  python3 make_numbers_extra.py
"""
import json
from pathlib import Path

REPO = Path(__file__).resolve().parents[3]
OUT = Path(__file__).resolve().parent / "numbers_extra.tex"

WORD = {"48": "FortyEight", "64": "SixtyFour", "96": "NinetySix",
        "128": "OneTwoEight"}
TAG = {"llasa1b": "LlasaOneB", "llasa3b": "LlasaThreeB",
       "llasa8b": "LlasaEightB", "qwen06b": "QwenZeroSixB",
       "qwen17b": "QwenOneSevenB"}


def num(v, nd):
    return f"{v:.{nd}f}"


macros = {}

he = json.loads((REPO / "data/results/horizon_ext.json").read_text())
mk = he["median_by_k"]
for arm, tag in (("rep", "Rep"), ("ctl", "Ctl")):
    for k, w in WORD.items():
        v = mk[arm].get(k)
        if v is not None:
            macros[f"Ext{tag}{w}"] = num(v, 1)

nl = json.loads((REPO / "data/results/text_nll_independent.json").read_text())
sec = nl["secondary"]
macros["NllGptRep"] = num(sec["rep_mean"], 2)
macros["NllGptCtl"] = num(sec["ctl_mean"], 2)
macros["NllGptPct"] = num(100 * sec["frac_ctl_higher"], 0)
macros["NllPhiRep"] = num(nl["primary"]["rep_mean"], 2)
macros["NllPhiCtl"] = num(nl["primary"]["ctl_mean"], 2)

pc = json.loads((REPO / "data/results/probe_horizon_compare.json").read_text())
rows, ctl = pc["rows"], pc["control_ratios"]
for m, t in TAG.items():
    r = rows.get(f"past:{m}")
    if r is not None:
        macros[f"PhRep{t}"] = num(r["mae_ratio"], 2)
    if m in ctl:
        macros[f"PhCtl{t}"] = num(ctl[m], 2)

OUT.write_text(
    "% AUTO-GENERATED by make_numbers_extra.py -- do not edit.\n"
    + "".join(f"\\newcommand{{\\{k}}}{{{v}}}\n" for k, v in sorted(macros.items())))
print(f"wrote {OUT} ({len(macros)} macros)")
